// Mock seed data for development / demo mode (no DB required)
import {
  Organization,
  Opportunity,
  NewsItem,
  Presentation,
  Task,
  DashboardStats,
} from "@/types";

export const MOCK_ORGS: Organization[] = [
  {
    id: "1",
    name: "Ayuntamiento de Madrid",
    logo: null,
    website: "https://www.madrid.es",
    country: "Spain",
    city: "Madrid",
    lat: 40.4168,
    lng: -3.7038,
    type: "GOVERNMENT",
    sector: "Urban Governance",
    description: "Gobierno local de Madrid, capital de España.",
    status: "ACTIVE_CLIENT",
    priority: "STRATEGIC",
    source: "Direct",
    ownerId: "u1",
    notes: "Contrato activo para análisis urbano del Plan Estratégico 2030.",
    lastContact: "2026-04-20",
    nextAction: "Presentar resultados fase 2",
    createdAt: "2024-01-10T10:00:00Z",
    updatedAt: "2026-04-20T10:00:00Z",
  },
  {
    id: "2",
    name: "ADNEC Group",
    logo: null,
    website: "https://www.adnec.ae",
    country: "UAE",
    city: "Abu Dhabi",
    lat: 24.4539,
    lng: 54.3773,
    type: "REAL_ESTATE_DEVELOPER",
    sector: "Real Estate & Events",
    description: "Desarrollador inmobiliario y gestor de eventos en Abu Dhabi.",
    status: "PROSPECT",
    priority: "HIGH",
    source: "Referral",
    ownerId: "u1",
    notes: "Interés en urban analytics para su masterplan.",
    lastContact: "2026-03-15",
    nextAction: "Enviar propuesta de servicios",
    createdAt: "2026-02-01T10:00:00Z",
    updatedAt: "2026-03-15T10:00:00Z",
  },
  {
    id: "3",
    name: "UN-Habitat",
    logo: null,
    website: "https://unhabitat.org",
    country: "Kenya",
    city: "Nairobi",
    lat: -1.286389,
    lng: 36.817223,
    type: "MULTILATERAL",
    sector: "Urban Development",
    description: "Programa de las Naciones Unidas para los Asentamientos Humanos.",
    status: "STRATEGIC_PARTNER",
    priority: "STRATEGIC",
    source: "Conference",
    ownerId: "u1",
    notes: "Partner en iniciativas de ciudades sostenibles.",
    lastContact: "2026-04-01",
    nextAction: "Reunión Q2 sobre programa de datos urbanos",
    createdAt: "2023-06-01T10:00:00Z",
    updatedAt: "2026-04-01T10:00:00Z",
  },
  {
    id: "4",
    name: "Merlin Properties",
    logo: null,
    website: "https://www.merlinproperties.com",
    country: "Spain",
    city: "Barcelona",
    lat: 41.3851,
    lng: 2.1734,
    type: "REAL_ESTATE_DEVELOPER",
    sector: "Real Estate",
    description: "Socimi española líder en real estate comercial y logístico.",
    status: "CONTACTED",
    priority: "HIGH",
    source: "LinkedIn",
    ownerId: "u1",
    notes: "Contacto con Director de Estrategia. Interés en analytics de portfolio.",
    lastContact: "2026-04-10",
    nextAction: "Follow-up call esta semana",
    createdAt: "2026-03-01T10:00:00Z",
    updatedAt: "2026-04-10T10:00:00Z",
  },
  {
    id: "5",
    name: "MIT Media Lab",
    logo: null,
    website: "https://media.mit.edu",
    country: "United States",
    city: "Cambridge",
    lat: 42.3601,
    lng: -71.0942,
    type: "ACADEMIC",
    sector: "Research & Innovation",
    description: "Laboratorio de investigación avanzada del MIT.",
    status: "PROSPECT",
    priority: "MEDIUM",
    source: "Conference",
    ownerId: "u1",
    notes: "Posible colaboración en proyectos de urban AI.",
    lastContact: "2026-02-20",
    nextAction: "Explorar grant conjunto",
    createdAt: "2026-01-15T10:00:00Z",
    updatedAt: "2026-02-20T10:00:00Z",
  },
  {
    id: "6",
    name: "Singapore Urban Redevelopment Authority",
    logo: null,
    website: "https://www.ura.gov.sg",
    country: "Singapore",
    city: "Singapore",
    lat: 1.3521,
    lng: 103.8198,
    type: "GOVERNMENT",
    sector: "Urban Planning",
    description: "Autoridad de planificación urbana de Singapur.",
    status: "MEETING_SCHEDULED",
    priority: "STRATEGIC",
    source: "Conference",
    ownerId: "u1",
    notes: "Interés en plataforma de digital twin para master planning.",
    lastContact: "2026-04-18",
    nextAction: "Presentación el 5 de mayo",
    createdAt: "2026-03-10T10:00:00Z",
    updatedAt: "2026-04-18T10:00:00Z",
  },
  {
    id: "7",
    name: "Blackstone Real Estate",
    logo: null,
    website: "https://www.blackstone.com",
    country: "United States",
    city: "New York",
    lat: 40.7128,
    lng: -74.006,
    type: "INVESTMENT_FUND",
    sector: "Investment",
    description: "Fondo de inversión inmobiliaria global líder.",
    status: "PROSPECT",
    priority: "HIGH",
    source: "LinkedIn",
    ownerId: "u1",
    notes: "Contacto a través de red de alumni Harvard.",
    lastContact: "2026-04-05",
    nextAction: "Enviar deck de servicios para fondos",
    createdAt: "2026-04-01T10:00:00Z",
    updatedAt: "2026-04-05T10:00:00Z",
  },
  {
    id: "8",
    name: "Mairie de Paris",
    logo: null,
    website: "https://www.paris.fr",
    country: "France",
    city: "Paris",
    lat: 48.8566,
    lng: 2.3522,
    type: "GOVERNMENT",
    sector: "Urban Governance",
    description: "Gobierno municipal de París.",
    status: "PROPOSAL_SENT",
    priority: "HIGH",
    source: "Direct",
    ownerId: "u1",
    notes: "Propuesta enviada para análisis de movilidad urbana.",
    lastContact: "2026-04-22",
    nextAction: "Seguimiento propuesta",
    createdAt: "2026-01-20T10:00:00Z",
    updatedAt: "2026-04-22T10:00:00Z",
  },
  {
    id: "9",
    name: "Neom",
    logo: null,
    website: "https://www.neom.com",
    country: "Saudi Arabia",
    city: "Tabuk",
    lat: 28.2697,
    lng: 36.1453,
    type: "URBAN_DEVELOPER",
    sector: "Smart City",
    description: "Proyecto de ciudad del futuro en Arabia Saudí.",
    status: "PROSPECT",
    priority: "STRATEGIC",
    source: "Conference",
    ownerId: "u1",
    notes: "Contacto inicial en Smart City Expo. Gran oportunidad.",
    lastContact: "2026-03-30",
    nextAction: "Preparar propuesta específica para THE LINE",
    createdAt: "2026-02-15T10:00:00Z",
    updatedAt: "2026-03-30T10:00:00Z",
  },
  {
    id: "10",
    name: "Ayuntamiento de Barcelona",
    logo: null,
    website: "https://www.barcelona.cat",
    country: "Spain",
    city: "Barcelona",
    lat: 41.3851,
    lng: 2.1734,
    type: "GOVERNMENT",
    sector: "Urban Governance",
    description: "Gobierno municipal de Barcelona.",
    status: "ACTIVE_CLIENT",
    priority: "HIGH",
    source: "Direct",
    ownerId: "u1",
    notes: "Proyecto de movilidad sostenible en curso.",
    lastContact: "2026-04-15",
    nextAction: "Entrega informe mensual",
    createdAt: "2023-09-01T10:00:00Z",
    updatedAt: "2026-04-15T10:00:00Z",
  },
];

export const MOCK_OPPORTUNITIES: Opportunity[] = [
  {
    id: "o1",
    name: "Digital Twin - Singapur URA",
    organizationId: "6",
    country: "Singapore",
    city: "Singapore",
    description: "Implementación de plataforma digital twin para planificación urbana.",
    value: 850000,
    probability: 60,
    status: "MEETING",
    closeDate: "2026-08-01",
    ownerId: "u1",
    nextAction: "Presentación el 5 de mayo",
    source: "Conference",
    notes: "Oportunidad estratégica. Requiere equipo técnico senior.",
    createdAt: "2026-03-10T10:00:00Z",
    updatedAt: "2026-04-18T10:00:00Z",
    organization: { id: "6", name: "Singapore Urban Redevelopment Authority" },
    owner: { id: "u1", name: "Pablo Roca" },
  },
  {
    id: "o2",
    name: "Urban Analytics - Paris Movilidad",
    organizationId: "8",
    country: "France",
    city: "Paris",
    description: "Análisis de patrones de movilidad y propuesta de intervenciones.",
    value: 320000,
    probability: 45,
    status: "PROPOSAL",
    closeDate: "2026-06-15",
    ownerId: "u1",
    nextAction: "Reunión de seguimiento propuesta",
    source: "Direct",
    notes: "Competencia con consultoras locales.",
    createdAt: "2026-01-20T10:00:00Z",
    updatedAt: "2026-04-22T10:00:00Z",
    organization: { id: "8", name: "Mairie de Paris" },
    owner: { id: "u1", name: "Pablo Roca" },
  },
  {
    id: "o3",
    name: "Real Estate Strategy - ADNEC",
    organizationId: "2",
    country: "UAE",
    city: "Abu Dhabi",
    description: "Análisis estratégico para masterplan del nuevo campus ADNEC.",
    value: 450000,
    probability: 30,
    status: "INITIAL_CONTACT",
    closeDate: "2026-09-30",
    ownerId: "u1",
    nextAction: "Enviar propuesta detallada",
    source: "Referral",
    notes: "",
    createdAt: "2026-02-01T10:00:00Z",
    updatedAt: "2026-03-15T10:00:00Z",
    organization: { id: "2", name: "ADNEC Group" },
    owner: { id: "u1", name: "Pablo Roca" },
  },
  {
    id: "o4",
    name: "Smart City Program - NEOM THE LINE",
    organizationId: "9",
    country: "Saudi Arabia",
    city: "Tabuk",
    description: "Consultoría estratégica para planificación de THE LINE.",
    value: 2000000,
    probability: 20,
    status: "RESEARCH",
    closeDate: "2026-12-31",
    ownerId: "u1",
    nextAction: "Preparar propuesta específica",
    source: "Conference",
    notes: "Alta complejidad política. Requiere partners locales.",
    createdAt: "2026-02-15T10:00:00Z",
    updatedAt: "2026-03-30T10:00:00Z",
    organization: { id: "9", name: "Neom" },
    owner: { id: "u1", name: "Pablo Roca" },
  },
  {
    id: "o5",
    name: "Portfolio Analytics - Blackstone",
    organizationId: "7",
    country: "United States",
    city: "New York",
    description: "Análisis de portfolio inmobiliario para decisiones de inversión.",
    value: 600000,
    probability: 25,
    status: "IDENTIFIED",
    closeDate: "2026-10-31",
    ownerId: "u1",
    nextAction: "Enviar deck de servicios",
    source: "LinkedIn",
    notes: "",
    createdAt: "2026-04-01T10:00:00Z",
    updatedAt: "2026-04-05T10:00:00Z",
    organization: { id: "7", name: "Blackstone Real Estate" },
    owner: { id: "u1", name: "Pablo Roca" },
  },
];

export const MOCK_NEWS: NewsItem[] = [
  {
    id: "n1",
    title: "Singapore launches $1B Smart City data initiative",
    source: "The Straits Times",
    url: "https://straitstimes.com",
    publishedAt: "2026-04-25",
    summary: "Singapore announces a major investment in urban data infrastructure and digital twins.",
    country: "Singapore",
    city: "Singapore",
    sector: "Smart City",
    relevance: 9,
    opportunityType: "SMART_CITY_PROGRAM",
    nextAction: "Contactar URA para posicionarnos en licitación",
    status: "SAVED",
    assigneeId: "u1",
    aiSummary: "Alta relevancia. Aretian puede presentar sus capacidades en urban analytics y digital twin.",
    aiTags: ["digital-twin", "smart-city", "singapore", "data"],
    createdAt: "2026-04-25T10:00:00Z",
    updatedAt: "2026-04-25T10:00:00Z",
  },
  {
    id: "n2",
    title: "EU Urban Mobility Mission abre convocatoria de €500M",
    source: "European Commission",
    url: "https://ec.europa.eu",
    publishedAt: "2026-04-20",
    summary: "La Comisión Europea lanza nueva convocatoria para proyectos de movilidad urbana sostenible.",
    country: "EU",
    city: null,
    sector: "Mobility",
    relevance: 8,
    opportunityType: "FUNDING_OPPORTUNITY",
    nextAction: "Analizar requisitos y explorar consorcio",
    status: "UNREVIEWED",
    assigneeId: null,
    aiSummary: "Oportunidad de funding para proyectos de movilidad. Aretian podría liderar o co-liderar consorcio.",
    aiTags: ["EU", "mobility", "funding", "grant"],
    createdAt: "2026-04-20T10:00:00Z",
    updatedAt: "2026-04-20T10:00:00Z",
  },
  {
    id: "n3",
    title: "Saudi Arabia accelerates NEOM construction timeline",
    source: "Bloomberg",
    url: "https://bloomberg.com",
    publishedAt: "2026-04-18",
    summary: "NEOM accelerates development of THE LINE and OXAGON, seeking international urban consultants.",
    country: "Saudi Arabia",
    city: "Tabuk",
    sector: "Smart City",
    relevance: 9,
    opportunityType: "URBAN_DEVELOPMENT_PROJECT",
    nextAction: "Preparar propuesta urgente",
    status: "SAVED",
    assigneeId: "u1",
    aiSummary: "Muy alta relevancia. Confirma actividad en NEOM. Ventana de oportunidad.",
    aiTags: ["neom", "smart-city", "saudi-arabia", "urban-development"],
    createdAt: "2026-04-18T10:00:00Z",
    updatedAt: "2026-04-18T10:00:00Z",
  },
];

export const MOCK_PRESENTATIONS: Presentation[] = [
  {
    id: "p1",
    title: "Aretian Corporate Overview 2026",
    description: "Presentación general de Aretian: misión, servicios, casos de uso y equipo.",
    fileUrl: null,
    fileName: "Aretian_Corporate_2026.pdf",
    targetType: "OTHER",
    sector: "General",
    region: "Global",
    language: "en",
    services: ["Urban Analytics", "Strategic Planning", "Digital Twin"],
    version: "3.2",
    status: "ACTIVE",
    createdAt: "2026-01-01T10:00:00Z",
    updatedAt: "2026-04-01T10:00:00Z",
  },
  {
    id: "p2",
    title: "Aretian for Governments",
    description: "Deck específico para gobiernos locales y regionales.",
    fileUrl: null,
    fileName: "Aretian_Governments_2026.pdf",
    targetType: "GOVERNMENT",
    sector: "Urban Governance",
    region: "Global",
    language: "en",
    services: ["Urban Analytics", "Policy Design", "Master Planning"],
    version: "2.1",
    status: "ACTIVE",
    createdAt: "2026-01-15T10:00:00Z",
    updatedAt: "2026-03-20T10:00:00Z",
  },
  {
    id: "p3",
    title: "Real Estate Analytics & Strategy",
    description: "Servicios de Aretian para desarrolladores y fondos inmobiliarios.",
    fileUrl: null,
    fileName: "Aretian_RealEstate_2026.pdf",
    targetType: "REAL_ESTATE_DEVELOPER",
    sector: "Real Estate",
    region: "Global",
    language: "en",
    services: ["Real Estate Analytics", "Investment Strategy", "Location Intelligence"],
    version: "1.8",
    status: "ACTIVE",
    createdAt: "2026-02-01T10:00:00Z",
    updatedAt: "2026-04-10T10:00:00Z",
  },
  {
    id: "p4",
    title: "Smart Cities & Digital Twin Platform",
    description: "Capacidades de Aretian en smart cities y gemelos digitales.",
    fileUrl: null,
    fileName: "Aretian_SmartCities_2026.pdf",
    targetType: "SMART_CITY",
    sector: "Smart City",
    region: "Global",
    language: "en",
    services: ["Digital Twin", "Data Platform", "Urban Analytics"],
    version: "2.0",
    status: "ACTIVE",
    createdAt: "2026-02-15T10:00:00Z",
    updatedAt: "2026-04-15T10:00:00Z",
  },
];

export const MOCK_TASKS: Task[] = [
  {
    id: "t1",
    title: "Enviar presentación a ADNEC Group",
    description: "Enviar el deck de Real Estate Strategy personalizado para Abu Dhabi.",
    ownerId: "u1",
    dueDate: "2026-05-05",
    priority: "HIGH",
    status: "PENDING",
    organizationId: "2",
    opportunityId: "o3",
    newsItemId: null,
    createdAt: "2026-04-29T10:00:00Z",
    updatedAt: "2026-04-29T10:00:00Z",
    owner: { id: "u1", name: "Pablo Roca" },
  },
  {
    id: "t2",
    title: "Preparar presentación para reunión Singapur",
    description: "Adaptar deck de Smart Cities para URA Singapore, incluir casos de uso asiáticos.",
    ownerId: "u1",
    dueDate: "2026-05-03",
    priority: "STRATEGIC",
    status: "IN_PROGRESS",
    organizationId: "6",
    opportunityId: "o1",
    newsItemId: null,
    createdAt: "2026-04-20T10:00:00Z",
    updatedAt: "2026-04-28T10:00:00Z",
    owner: { id: "u1", name: "Pablo Roca" },
  },
  {
    id: "t3",
    title: "Revisar convocatoria EU Urban Mobility",
    description: "Analizar requisitos y evaluar si Aretian puede presentarse como lead.",
    ownerId: "u1",
    dueDate: "2026-05-10",
    priority: "HIGH",
    status: "PENDING",
    organizationId: null,
    opportunityId: null,
    newsItemId: "n2",
    createdAt: "2026-04-21T10:00:00Z",
    updatedAt: "2026-04-21T10:00:00Z",
    owner: { id: "u1", name: "Pablo Roca" },
  },
];

export const MOCK_STATS: DashboardStats = {
  totalClients: 10,
  activeClients: 2,
  prospects: 5,
  pastClients: 0,
  openOpportunities: 5,
  strategicPartners: 1,
  pendingTasks: 3,
  recentNews: 3,
  countriesCount: 8,
  pipelineByStatus: [
    { status: "IDENTIFIED", count: 1 },
    { status: "RESEARCH", count: 1 },
    { status: "INITIAL_CONTACT", count: 1 },
    { status: "MEETING", count: 1 },
    { status: "PROPOSAL", count: 1 },
    { status: "NEGOTIATION", count: 0 },
    { status: "WON", count: 0 },
  ],
  clientsByType: [
    { type: "GOVERNMENT", count: 4 },
    { type: "REAL_ESTATE_DEVELOPER", count: 2 },
    { type: "INVESTMENT_FUND", count: 1 },
    { type: "MULTILATERAL", count: 1 },
    { type: "ACADEMIC", count: 1 },
    { type: "URBAN_DEVELOPER", count: 1 },
  ],
  clientsByPriority: [
    { priority: "STRATEGIC", count: 3 },
    { priority: "HIGH", count: 4 },
    { priority: "MEDIUM", count: 2 },
    { priority: "LOW", count: 1 },
  ],
};
